# Generated by Django 3.2.8 on 2021-10-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211030_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateField(default='2021-03-03'),
            preserve_default=False,
        ),
    ]
