# Generated by Django 3.2.8 on 2021-10-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='druft',
            field=models.BooleanField(default=False),
        ),
    ]
